DECLARE

  VID_FUNC &&OWNER_NAME..TABLE_NAME_01.ID_FUNC%TYPE;

BEGIN

  FOR CURSOR_DATA IN (SELECT * FROM &&OWNER_NAME..TABLE_NAME_02) LOOP
  
    BEGIN
      SELECT ID_FUNC
        INTO VID_FUNC
        FROM &&OWNER_NAME..TABLE_NAME_01
       WHERE S_FUNC_NAME = 'XXX';
    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        VID_FUNC := NULL;
    END;
  
    FOR C IN (SELECT ID_DOMAIN
                FROM &&OWNER_NAME..TABLE_NAME_03
               WHERE S_DOM_GROUP = 'XXX'
                 AND ID_PARTITION = CURSOR_DATA.ID_PARTITION
                 AND S_DOM_CODE IN ('XXX001')) LOOP
      BEGIN
		DELETE FROM &&OWNER_NAME..TABLE_NAME_04
		WHERE ID_DOMAIN = C.ID_DOMAIN
		AND ID_FUNC     = VID_FUNC
		AND ID_PARTITION    = CURSOR_DATA.ID_PARTITION;
      END;
    END LOOP;
  
  END LOOP;

END;
/