DECLARE
  VID_FUNCTIONALITY &&OWNER_NAME..TABLE_NAME_01.ID_FUNCTIONALITY%TYPE;

BEGIN

  FOR CDATA IN (SELECT * FROM &&OWNER_NAME..TABLE_NAME_02) LOOP

  BEGIN
    SELECT ID_FUNCTIONALITY
      INTO VID_FUNCTIONALITY
      FROM &&OWNER_NAME..TABLE_NAME_01
     WHERE S_FUNCTIONALITY_NAME = 'FuncName01';
	 EXCEPTION
    WHEN NO_DATA_FOUND THEN
      VID_FUNCTIONALITY := NULL;  
  END;

  FOR C IN (SELECT ID_BUSINESS_DOMAIN
              FROM &&OWNER_NAME..TABLE_NAME_03
             WHERE S_DOMAIN_GROUP = 'XXX'
			   AND ID_SAAS_PARTITION = cData.Id_Saas_Partition
               AND S_DOMAIN_CODE IN ('XXX001','XXX002')) LOOP
    BEGIN
      INSERT INTO &&OWNER_NAME..TABLE_NAME_04
        (ID_BUSINESS_DOMAIN,
         ID_FUNCTIONALITY,
         D_CREATION_DATE,
         S_CREATED_BY, 
		 ID_SAAS_PARTITION)
      VALUES
        (C.ID_BUSINESS_DOMAIN, VID_FUNCTIONALITY, SYSDATE, 'INITIAL DATA', cData.Id_Saas_Partition);
    EXCEPTION
      WHEN DUP_VAL_ON_INDEX THEN
        NULL;
    END;
  END LOOP;
  
  END LOOP;

END;
/