DECLARE
  VID_FUN &&OWNER_NAME..TABLE_NAME_01.ID_FUN%TYPE;

BEGIN

  FOR CURSOR_DATA IN (SELECT * FROM &&OWNER_NAME..TABLE_NAME_02) LOOP

  BEGIN
    SELECT ID_FUN
      INTO VID_FUN
      FROM &&OWNER_NAME..TABLE_NAME_01
     WHERE S_FUNC_NAME = 'FuncName01';
	 EXCEPTION
    WHEN NO_DATA_FOUND THEN
      VID_FUN := NULL;  
  END;

  FOR C IN (SELECT ID_DOMAIN
              FROM &&OWNER_NAME..TABLE_NAME_03
             WHERE S_DOM_GROUP = 'XXX'
			   AND ID_PARTITION = CURSOR_DATA.ID_PARTITION
               AND S_DOM_CODE IN ('XXX001','XXX002')) LOOP
    BEGIN
      INSERT INTO &&OWNER_NAME..TABLE_NAME_04
        (ID_DOMAIN,
         ID_FUN,
         D_CREATION_DATE,
         S_CREATED_BY, 
		 ID_PARTITION)
      VALUES
        (C.ID_DOMAIN, VID_FUN, SYSDATE, 'INITIAL DATA', CURSOR_DATA.ID_PARTITION);
    EXCEPTION
      WHEN DUP_VAL_ON_INDEX THEN
        NULL;
    END;
  END LOOP;
  
  END LOOP;

END;
/