CREATE TABLE OWNER_NAME.TABLE_NAME
(
  ID          NUMBER(10) NOT NULL,
  COLUMN_NAME DATE NOT NULL
)
  PARTITION BY RANGE (COLUMN_NAME) (   
   PARTITION PARTITION_NAME_01 VALUES LESS THAN (TO_DATE(' 2005-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    TABLESPACE OWNER_NAME.TABLESPACE_NAME_01
    PCTFREE 10 
    INITRANS 2
    MAXTRANS 255 
    NOLOGGING
    STORAGE
    (
      INITIAL 5M
      NEXT 5M
      MINEXTENTS 1
      MAXEXTENTS UNLIMITED
      PCTINCREASE 0
    ),
   PARTITION PARTITION_NAME_02 VALUES LESS THAN (TO_DATE(' 2013-11-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    TABLESPACE OWNER_NAME.TABLESPACE_NAME_02
    PCTFREE 10 
    INITRANS 2
    MAXTRANS 255 
    NOLOGGING
    STORAGE
    (
      INITIAL 10M
      NEXT 10M
      MINEXTENTS 1
      MAXEXTENTS UNLIMITED
      PCTINCREASE 0
    )
);